Layout cleanup
Kenneth-Ngcobo/book-connect-app pull request #2
Opened 2023-08-15 09:43 UTC by Kenneth-Ngcobo

2023-08-15 11:11 UTC, Cbazil requested changes
Can you remove the test text added "Hey2 45454"

2023-08-15 11:24 UTC, Kenneth-Ngcobo commented
> Can you remove the test text added "Hey2 45454" from README.md

Done

2023-08-15 12:24 UTC, Cbazil approved these changes

2023-08-16 09:23 UTC, BoredBarney approved these changes

2023-08-16 09:28 UTC, merged